services:
  dev-server:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
  prod-server:
    build:
      context: .
      dockerfile: 'Dockerfile.prod'
    ports:
      - '8080:8080'
